//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sporting
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table
    {
        public int Id { get; set; }
        public string VidSporta { get; set; }
        public string Komand { get; set; }
        public string NameOfSection { get; set; }
        public string Place { get; set; }
        public string Contact { get; set; }
        public Nullable<int> Podgotovka { get; set; }
        public Nullable<int> Travmoopasnost { get; set; }
        public Nullable<int> Chastota { get; set; }
        public Nullable<int> AgeMin { get; set; }
        public Nullable<int> CenaMin { get; set; }
        public Nullable<int> CenaEkipMin { get; set; }
        public string Rayon { get; set; }
        public Nullable<int> AgeMax { get; set; }
        public Nullable<int> CenaMax { get; set; }
        public Nullable<int> CenaEkipMax { get; set; }
    }
}
